In [1]:
# transform univariate time series to supervised learning problem
from numpy import array
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
# split a univariate sequence into samples
def split_sequence(sequence, n_steps):
    X, y = list(), list()
    for i in range(len(sequence)):
        # find the end of this pattern
        end_ix = i + n_steps
        # check if we are beyond the sequence
        if end_ix > len(sequence)-1:
            break
        # gather input and output parts of the pattern
        seq_x, seq_y = sequence[i:end_ix], sequence[end_ix]
        X.append(seq_x)
        y.append(seq_y)
    return array(X), array(y)

In [3]:
# define univariate time series
series = array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(series.shape)
# transform to a supervised learning problem
X, y = split_sequence(series, 3)
print(X.shape, y.shape)
# show each sample
for i in range(len(X)):
    print(X[i], y[i])

(10,)
(7, 3) (7,)
[1 2 3] 4
[2 3 4] 5
[3 4 5] 6
[4 5 6] 7
[5 6 7] 8
[6 7 8] 9
[7 8 9] 10


In [4]:
# define univariate time series
series = array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(series.shape)
# transform to a supervised learning problem
X, y = split_sequence(series, 3)
print(X.shape, y.shape)
# transform input from [samples, features] to [samples, timesteps, features]
X = X.reshape((X.shape[0], X.shape[1], 1))
print(X.shape)

(10,)
(7, 3) (7,)
(7, 3, 1)


In [5]:
case = pd.read_csv('data/new/case_maret_july.csv')

In [6]:
case.shape

(423, 2)

In [7]:
list_case = case['case'].tolist()

In [8]:
print(list_case)

[38, 50, 14, 44, 36, 51, 71, 46, 43, 51, 37, 98, 26, 14, 75, 93, 81, 81, 80, 148, 144, 109, 167, 91, 93, 179, 160, 107, 98, 223, 153, 79, 131, 79, 167, 120, 107, 99, 76, 65, 86, 118, 83, 105, 145, 72, 62, 55, 169, 68, 66, 126, 57, 182, 55, 108, 134, 180, 62, 116, 127, 74, 57, 97, 70, 96, 127, 118, 67, 61, 137, 103, 124, 98, 121, 111, 76, 80, 61, 84, 102, 160, 91, 239, 147, 129, 76, 120, 115, 105, 124, 117, 176, 140, 178, 127, 127, 166, 154, 195, 168, 213, 132, 95, 196, 206, 195, 147, 215, 256, 231, 199, 344, 290, 239, 359, 404, 278, 275, 259, 293, 241, 331, 313, 361, 441, 376, 416, 285, 393, 378, 472, 412, 585, 299, 432, 374, 379, 489, 466, 357, 597, 658, 721, 472, 479, 471, 578, 621, 575, 598, 518, 538, 505, 565, 595, 641, 601, 637, 659, 636, 711, 820, 816, 888, 1114, 1029, 941, 1053, 1406, 895, 842, 1245, 1105, 1015, 1026, 1450, 1034, 1440, 1103, 1062, 1027, 1505, 1014, 1403, 932, 1079, 1310, 1122, 1187, 1133, 1289, 1257, 1186, 807, 1132, 1059, 1153, 1098, 1165, 1430, 822, 1007, 1340

In [22]:
samples = list()
samples.append(list_case)
print(samples)

[[38, 50, 14, 44, 36, 51, 71, 46, 43, 51, 37, 98, 26, 14, 75, 93, 81, 81, 80, 148, 144, 109, 167, 91, 93, 179, 160, 107, 98, 223, 153, 79, 131, 79, 167, 120, 107, 99, 76, 65, 86, 118, 83, 105, 145, 72, 62, 55, 169, 68, 66, 126, 57, 182, 55, 108, 134, 180, 62, 116, 127, 74, 57, 97, 70, 96, 127, 118, 67, 61, 137, 103, 124, 98, 121, 111, 76, 80, 61, 84, 102, 160, 91, 239, 147, 129, 76, 120, 115, 105, 124, 117, 176, 140, 178, 127, 127, 166, 154, 195, 168, 213, 132, 95, 196, 206, 195, 147, 215, 256, 231, 199, 344, 290, 239, 359, 404, 278, 275, 259, 293, 241, 331, 313, 361, 441, 376, 416, 285, 393, 378, 472, 412, 585, 299, 432, 374, 379, 489, 466, 357, 597, 658, 721, 472, 479, 471, 578, 621, 575, 598, 518, 538, 505, 565, 595, 641, 601, 637, 659, 636, 711, 820, 816, 888, 1114, 1029, 941, 1053, 1406, 895, 842, 1245, 1105, 1015, 1026, 1450, 1034, 1440, 1103, 1062, 1027, 1505, 1014, 1403, 932, 1079, 1310, 1122, 1187, 1133, 1289, 1257, 1186, 807, 1132, 1059, 1153, 1098, 1165, 1430, 822, 1007, 134

In [23]:
data = array(samples)
data = data.reshape((len(samples), (len(list_case)), 1))
print(data.shape)

(1, 423, 1)
